### ISSUE TITLE
JSON Export unreadable by chrome://tracing

### ISSUE THREAD

**Issue by DonGoddard** [Unity-Technologies/com.unity.editoriterationprofiler#9]
Errors with every JSON export. Here's one:

Error
✕
While importing:
SyntaxError: Unexpected token I in JSON at position 739
    at JSON.parse (<anonymous>)
    at new TraceEventImporter (chrome://tracing/tracing.js:6269:19)
    at Import.createImporter_ (chrome://tracing/tracing.js:2023:8)
    at chrome://tracing/tracing.js:2015:167
    at Task.run (chrome://tracing/tracing.js:3266:95)
    at runAnother (chrome://tracing/tracing.js:3269:371)
    at runTask (chrome://tracing/tracing.js:3031:57)
    at processIdleWork (chrome://tracing/tracing.js:3036:116)
    at window.requestIdleCallback.timeout (chrome://tracing/tracing.js:3029:81)
OK

**Comment by Rares95** [comment]
There is probably an unexpected comma somewhere.

Unfortunately, we are working on other critical things (such as improving the iteration time from our side), so we don't have time to fix this. However, you can fix it yourself if you feel adventurous. I will review any PR that gets pushed! :)

**Comment by rarepops** [comment]
Also do you use a specific language for your system? OS? Unity Version etc?

Better yet, can you simply upload the output file? It's easier to find the issue by just looking at the file where the issue is reported. 9/10 times it's an unexpected comma

**Comment by Rares95** [comment]
Better yet, can you simply upload the output file?
